enum HablaErrorCodes {
    AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
    AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
    NOT_FOUND_ERROR = 'NOT_FOUND_ERROR', 
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    MISSING_LOCATION_ERROR = 'MISSING_LOCATION_ERROR',
    INSUFFICENT_SCORE_ERROR = 'INSUFFICENT_SCORE_ERROR'
}

export default HablaErrorCodes;